// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Edited to load .env.local instead of .env, matching the convention the
// rest of this Next.js project uses (see .env.local.example).
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
